services:
  azuresqledge:
    image: mcr.microsoft.com/azure-sql-edge
    container_name: azuresqledge
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password123!
    ports:
      - "1433:1433"
    volumes:
      - sqldata:/var/opt/mssql
    restart: always
    networks:
      - mynetwork

  mybackendapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mybackendapi
    ports:
      - "5000:80"
    depends_on:
      - azuresqledge
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=azuresqledge;Database=MyBackendDb;User Id=sa;Password=Password123!;TrustServerCertificate=True;
    restart: always
    volumes:
      - ./MyBackendApi/appsettings.json:/app/appsettings.json
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  sqldata:
    driver: local 